import type { SchemaTypeDefinition } from "sanity"

// Review schema
const review = {
  name: "review",
  title: "Reviews",
  type: "document",
  fields: [
    {
      name: "title",
      title: "Title",
      type: "string",
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "slug",
      title: "Slug",
      type: "slug",
      options: {
        source: "title",
        maxLength: 96,
      },
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "publishedAt",
      title: "Published at",
      type: "datetime",
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "excerpt",
      title: "Excerpt",
      type: "text",
      rows: 3,
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "mainImage",
      title: "Main image",
      type: "image",
      options: {
        hotspot: true,
      },
    },
    {
      name: "rating",
      title: "Rating",
      type: "number",
      validation: (Rule: any) => Rule.required().min(0).max(5),
    },
    {
      name: "product",
      title: "Product",
      type: "reference",
      to: [{ type: "product" }],
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "generatedContent",
      title: "Generated Content (Markdown)",
      type: "text",
      description: "Raw markdown generated by OpenAI",
    },
    {
      name: "sourcePrompt",
      title: "Source Prompt",
      type: "text",
      description: "The prompt used to generate this content",
    },
    {
      name: "sourceModel",
      title: "Source Model",
      type: "string",
      description: "LLM model used (e.g., gpt-4)",
    },
    {
      name: "content",
      title: "Content",
      type: "array",
      of: [
        {
          type: "block",
        },
        {
          type: "image",
          options: {
            hotspot: true,
          },
        },
      ],
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "pros",
      title: "Pros",
      type: "array",
      of: [{ type: "string" }],
    },
    {
      name: "cons",
      title: "Cons",
      type: "array",
      of: [{ type: "string" }],
    },
  ],
}

// Product schema
const product = {
  name: "product",
  title: "Products",
  type: "document",
  fields: [
    {
      name: "name",
      title: "Name",
      type: "string",
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "image",
      title: "Image",
      type: "image",
      options: {
        hotspot: true,
      },
    },
    {
      name: "price",
      title: "Price",
      type: "string",
    },
    {
      name: "brand",
      title: "Brand",
      type: "string",
    },
    {
      name: "size",
      title: "Size",
      type: "string",
    },
    {
      name: "affiliateLink",
      title: "Affiliate Link",
      type: "url",
    },
    {
      name: "asin",
      title: "Amazon ASIN",
      type: "string",
    },
    {
      name: "activeIngredient",
      title: "Active Ingredient",
      type: "string",
    },
    {
      name: "mechanism",
      title: "Mechanism of Action",
      type: "string",
    },
    {
      name: "category",
      title: "Category",
      type: "string",
    },
    {
      name: "useCases",
      title: "Use Cases",
      type: "array",
      of: [{ type: "reference", to: [{ type: "useCase" }] }],
    },
    {
      name: "form",
      title: "Form",
      type: "string",
    },
    {
      name: "applicationType",
      title: "Application Type",
      type: "string",
    },
    {
      name: "ingredients",
      title: "Ingredients",
      type: "array",
      of: [{ type: "reference", to: [{ type: "ingredient" }] }],
    },
    {
      name: "OTC",
      title: "OTC",
      type: "boolean",
    },
    {
      name: "isGeneric",
      title: "Generic",
      type: "boolean",
    },
    {
      name: "notes",
      title: "Notes",
      type: "text",
    },
    {
      name: "region",
      title: "Available Regions",
      type: "array",
      of: [{ type: "string" }],
      options: {
        layout: "tags",
      },
    }
  ],
}

// Use Case schema
const useCase = {
  name: "useCase",
  title: "Use Cases",
  type: "document",
  fields: [
    {
      name: "title",
      title: "Title",
      type: "string",
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "slug",
      title: "Slug",
      type: "slug",
      options: {
        source: "title",
        maxLength: 96,
      },
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "publishedAt",
      title: "Published at",
      type: "datetime",
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "excerpt",
      title: "Excerpt",
      type: "text",
      rows: 3,
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "mainImage",
      title: "Main image",
      type: "image",
      options: {
        hotspot: true,
      },
    },
    {
      name: "metaTitle",
      title: "Meta Title",
      type: "string",
    },
    {
      name: "metaDescription",
      title: "Meta Description",
      type: "text",
      rows: 3,
    },
    {
      name: "author",
      title: "Author",
      type: "string",
    },
    {
      name: "tags",
      title: "Tags",
      type: "array",
      of: [{ type: "string" }],
      options: {
        layout: "tags",
      },
    },
    {
      name: "categories",
      title: "Categories",
      type: "array",
      of: [{ type: "string" }],
      options: {
        layout: "tags",
      },
    },
    {
      name: "introduction",
      title: "Introduction",
      type: "array",
      of: [{ type: "block" }],
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "content",
      title: "Content",
      type: "array",
      of: [
        {
          type: "block",
        },
        {
          type: "image",
          options: {
            hotspot: true,
          },
        },
      ],
      validation: (Rule: any) => Rule.required(),
    },
  ],
}

// Comparison schema
const comparison = {
  name: "comparison",
  title: "Comparisons",
  type: "document",
  fields: [
    {
      name: "title",
      title: "Title",
      type: "string",
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "slug",
      title: "Slug",
      type: "slug",
      options: {
        source: "title",
        maxLength: 96,
      },
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "publishedAt",
      title: "Published at",
      type: "datetime",
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "excerpt",
      title: "Excerpt",
      type: "text",
      rows: 3,
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "mainImage",
      title: "Main image",
      type: "image",
      options: {
        hotspot: true,
      },
    },
    {
      name: "introduction",
      title: "Introduction",
      type: "array",
      of: [{ type: "block" }],
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "products",
      title: "Products",
      type: "array",
      of: [
        {
          type: "object",
          fields: [
            {
              name: "name",
              title: "Product Name",
              type: "string",
              validation: (Rule: any) => Rule.required(),
            },
            {
              name: "values",
              title: "Values",
              type: "object",
              fields: [
                { name: "price", title: "Price", type: "string" },
                { name: "rating", title: "Rating", type: "number" },
                { name: "effectiveness", title: "Effectiveness", type: "string" },
                { name: "sideEffects", title: "Side Effects", type: "string" },
                { name: "ingredients", title: "Key Ingredients", type: "string" },
                { name: "value", title: "Value for Money", type: "string" },
                { name: "ease", title: "Ease of Use", type: "string" },
              ],
            },
          ],
        },
      ],
    },
    {
      name: "criteria",
      title: "Comparison Criteria",
      type: "array",
      of: [
        {
          type: "object",
          fields: [
            {
              name: "name",
              title: "Name",
              type: "string",
              validation: (Rule: any) => Rule.required(),
            },
            {
              name: "key",
              title: "Key",
              type: "string",
              validation: (Rule: any) => Rule.required(),
            },
            {
              name: "type",
              title: "Type",
              type: "string",
              options: {
                list: [
                  { title: "Text", value: "text" },
                  { title: "Number", value: "number" },
                  { title: "Boolean", value: "boolean" },
                  { title: "Rating", value: "rating" },
                ],
              },
              validation: (Rule: any) => Rule.required(),
            },
          ],
        },
      ],
    },
    {
      name: "content",
      title: "Content",
      type: "array",
      of: [
        {
          type: "block",
        },
        {
          type: "image",
          options: {
            hotspot: true,
          },
        },
      ],
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "winner",
      title: "Winner",
      type: "reference",
      to: [{ type: "product" }],
    },
    {
      name: "winnerReason",
      title: "Winner Reason",
      type: "text",
    },
  ],
}

// Ingredient schema
const ingredient = {
  name: "ingredient",
  title: "Ingredients",
  type: "document",
  fields: [
    {
      name: "title",
      title: "Title",
      type: "string",
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "slug",
      title: "Slug",
      type: "slug",
      options: {
        source: "title",
        maxLength: 96,
      },
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "publishedAt",
      title: "Published at",
      type: "datetime",
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "excerpt",
      title: "Excerpt",
      type: "text",
      rows: 3,
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "mainImage",
      title: "Main image",
      type: "image",
      options: {
        hotspot: true,
      },
    },
    {
      name: "scientificName",
      title: "Scientific Name",
      type: "string",
    },
    {
      name: "origin",
      title: "Origin",
      type: "string",
    },
    {
      name: "category",
      title: "Category",
      type: "string",
    },
    {
      name: "benefits",
      title: "Benefits",
      type: "array",
      of: [{ type: "string" }],
    },
    {
      name: "sideEffects",
      title: "Side Effects",
      type: "array",
      of: [{ type: "string" }],
    },
    {
      name: "content",
      title: "Content",
      type: "array",
      of: [
        {
          type: "block",
        },
        {
          type: "image",
          options: {
            hotspot: true,
          },
        },
      ],
      validation: (Rule: any) => Rule.required(),
    },
  ],
}

// FAQ schema
const faq = {
  name: "faq",
  title: "FAQs",
  type: "document",
  fields: [
    {
      name: "title",
      title: "Title",
      type: "string",
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "slug",
      title: "Slug",
      type: "slug",
      options: {
        source: "title",
        maxLength: 96,
      },
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "publishedAt",
      title: "Published at",
      type: "datetime",
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "excerpt",
      title: "Excerpt",
      type: "text",
      rows: 3,
    },
    {
      name: "answer",
      title: "Answer",
      type: "array",
      of: [
        {
          type: "block",
        },
        {
          type: "image",
          options: {
            hotspot: true,
          },
        },
      ],
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: "sources",
      title: "Sources",
      type: "array",
      of: [
        {
          type: "object",
          fields: [
            {
              name: "title",
              title: "Title",
              type: "string",
            },
            {
              name: "url",
              title: "URL",
              type: "url",
            },
          ],
        },
      ],
    },
  ],
}

export const schema: { types: SchemaTypeDefinition[] } = {
  types: [review, product, useCase, comparison, ingredient, faq],
}
